---
title: "Análise de Aerodinâmica"
format:
  dashboard:
    theme:
      light: 
        - pulse
        - ../scss/main.scss
        - ../scss/modules/dashboard.scss
      dark:
        - darkly
        - ../scss/main.scss
        - ../scss/modules/dashboard.scss
editor_options:
  chunk_output_type: console
---

```{r}
#| context: setup
#| include: false
library(shiny)
library(bslib)
```

# Perfis

## Column {.tabset}

```{r}
#| title: Perfil 1

actionButton(
  "id",
  "Texto"
)
```

```{r}
#| title: Perfil 2

actionButton(
  "id",
  "Texto"
)
```

```{r}
#| title: Perfil 3

actionButton(
  "id",
  "Texto"
)
```

## Row

## Column

# Comparar Perfis

```{r}
#| content: card-toolbar
#| title: Configurações

selectInput( 
  "cmbSection", 
  "Seção do Avião:", 
  list(
    "Asa" = "wing",
    "Horizontal" = "backHorizontal",
    "Vertical" = "backVertical")
)

checkboxGroupInput( 
  "chkgrpProfiles", 
  "Visualizar Perfis:", 
  c( 
    "Perfil 1" = "profile1", 
    "Perfil 2" = "profile2", 
    "Perfil 3" = "profile3" 
  ) 
)
```

```{r}
renderPlot({
  if (input$cmbSection == "wing") {
    plot(dados_asa$x, dados_asa$y)
  }

  if (input$cmbSection == "backHorizontal") {
    plot(dados_horizontal$x, dados_horizontal$y)
  }

  if (input$cmbSection == "backVertical") {
    plot(dados_vertical$x, dados_vertical$y)
  }
})
```

