```{r}
#| context: setup
#| include: false

library(here)
```

#### Column {width="20%"}

##### Row {height="30%"}

```{r}
#| content: toolbar

tags$img(
  src = "www/resources/images/aircraft.jpg"
)
```

##### Row {height="70%"}

Lista de Símbolos

| Símbolo | Significado                     |
|---------|---------------------------------|
| CL      | Coeficiente de Sustentação (3D) |
| CD      | Coeficiente de Arrasto (3D)     |

#### Column {width="60%"}

##### Row {height="20%"}

```{r}
#| content: valuebox
#| title: CLmax

list(
  color = "primary",
  value = sprintf("%.2f", ponto_cl_max$CL)
)
```

```{r}
#| content: valuebox
#| title: α no CLmax

list(
  color = "primary",
  value = sprintf("%.1f°", ponto_cl_max$alpha)
)
```

```{r}
#| content: valuebox
#| title: (CD/CL)max

list(
  color = "primary",
  value = sprintf("%.2f", ponto_polar_melhor$cl_cd)
)
```

##### Row {height="80%"}

```{r}
plot_aircraft_cl_cd(df_3d)
```

#### Column {width="20%"}

##### Row {height="40%"}

```{r}
#| title: Gráfico de Sustentação
#| caption: Expanda para visualizar o gráfico de sustentação da aeronave completa.
plot_aircraft_cl_alpha(df_3d)
```

##### Row {height="60%"}

::: {}
:::

#### Column {width="0%"}
<!--
NÃO REMOVER ESTA COLUNA.

Por algum motivo insondável do Quarto Dashboard,
a remoção desta coluna quebra completamente o layout.
Se descobrir o motivo, me avise.
- Vini do passado
-->